default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: old_games_online_development

test:
  <<: *default
  database: old_games_online_test

production:
  <<: *default
  database: old_games_online_production
  username: old_games_online
  password: <%= ENV['old_games_online_DATABASE_PASSWORD'] %>
